/* File Automatically Generated by LSC. Please do not edit manually. */
export const generatedMenuItems = [
  {
    id: '<%= appNameSlug %>',
    route: '<%= appNameSlug %>',
    click: 'tenant-switch',
    text: '<%= appNamePascalCase %>',
    icon: 'icon-lsi-edit2'
  }
];
