/* File Automatically Generated by LSC. Please do not edit manually. */

import {Routes} from '@angular/router';

export const generatedRoutes: Routes = [
  {
    path: '<%= appNameSlug %>',
    loadChildren: () => import('@labshare/<%= appNameSlug %>').then(m => m.<%= appNamePascalCase %>Module)
  }
];
